CREATE TABLE IF NOT EXISTS "user" (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(32) NOT NULL DEFAULT '',
  `password` VARCHAR(128) NOT NULL DEFAULT '',
  `phone` VARCHAR(11) NOT NULL DEFAULT '',
  `nickname` VARCHAR(32) DEFAULT '',
  `avatar` VARCHAR(128) DEFAULT '',
  `role` TINYINT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `openid` VARCHAR(64) DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_username ON "user"(username);
CREATE UNIQUE INDEX IF NOT EXISTS idx_phone ON "user"(phone);
CREATE UNIQUE INDEX IF NOT EXISTS idx_openid ON "user"(openid);
