server:
  port: 8080

spring:
  application:
    name: campus-express-backend
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.25.111.156:3306/campus_express?useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Ma131419+
  
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      # data-locations: classpath:db/data.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
      db-type: mysql
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: campus-express-secret-key-2024-!@#abcXYZ
  expiration: 604800

wechat:
  appid: wxf75e60b7eab2499b
  secret: c7ae0fb7819190c6f8e019afd34b9379
  session-url: https://api.weixin.qq.com/sns/jscode2session
  access-token-url: https://api.weixin.qq.com/cgi-bin/token
  subscribe-send-url: https://api.weixin.qq.com/cgi-bin/message/subscribe/send?access_token=%s
  debug: false

obs:
  enabled: ${OBS_ENABLED:false}
  endpoint: obs.cn-north-4.myhuaweicloud.com
  access-key-id: ${OBS_ACCESS_KEY_ID:}
  secret-access-key: ${OBS_SECRET_ACCESS_KEY:}
  bucket-name: picture-64
  folder: campus-express/evidence
  url-prefix:
  local-dir: uploads/evidence

warning:
  webhook-url:
  scan-cron: 0 0 2 * * ?
  wechat:
    enabled: false
    template-id:
    page: pages/package/list/index
    miniprogram-state: formal
    lang: zh_CN
    title-field: thing1
    station-field: thing2
    code-field: character_string3
    date-field: time4
    remark-field: thing5

baidu:
  ocr:
    api-key: DTfR5EqnYhihCDUZ5mzuF5Ek
    secret-key: rffIP39mmOoFF13tnpZHZ4IFYBiOqkHj
    token-url: https://aip.baidubce.com/oauth/2.0/token
    general-url: https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic